
import '@servicenow/sdk/global'

import './security/roles.now.ts'
import './tables/salesforce-connection.now.ts'
import './tables/salesforce-object-config.now.ts'
import './tables/salesforce-record-link.now.ts'
import './tables/sync-config.now.ts'
import './tables/sync-event-queue.now.ts'
import './script-includes/salesforce-connection-service.now.ts'
import './script-includes/salesforce-oauth-service.now.ts'
import './script-includes/task-sync-service.now.ts'
import './script-includes/sync-event-queue-service.now.ts'
import './scripted-rest-apis/salesforce-integration.now.ts'
import './ui-pages/incident-manager.now.ts'
import './service-portal/peeklo-salesforce-connector-widget.now.ts'
import './business-rules/task-sync-create.now.ts'
import './business-rules/task-sync-update.now.ts'
import './business-rules/task-sync-delete.now.ts'
import './business-rules/sync-event-queue-create.now.ts'
import './business-rules/sync-event-queue-retry.now.ts'
import './business-rules/salesforce-object-config-cascade-delete.now.ts'
import './business-rules/salesforce-related-object-cascade-delete.now.ts'
import './acls/salesforce-selected-related-objects-acl.now.ts'