import '@servicenow/sdk/global'
import { Acl, RestApi } from '@servicenow/sdk/core'
import { salesforceIntegrationUserPaidRole } from '../security/roles.now'

const salesforceIntegrationRestEndpointAcl = Acl({
    $id: Now.ID['salesforce_integration_rest_endpoint_acl'],
    name: 'Salesforce Integration REST Endpoint',
    type: 'rest_endpoint',
    operation: 'execute',
    roles: [salesforceIntegrationUserPaidRole],
})

RestApi({
    $id: Now.ID['salesforce_integration_api'],
    name: 'salesforce_integration',
    serviceId: 'x_peekl_salesfor_0_salesforce_integratio',
    shortDescription: 'API for Salesforce integration - authentication and task type configuration',
    routes: [
        {
            $id: Now.ID['modal_bundle_route'],
            path: '/modal/bundle',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/modal-bundle-get.js'),
            shortDescription: 'Serves a hardcoded JS bundle for the React modal (no attachment needed)',
        },
        {
            $id: Now.ID['connection_init_route'],
            path: '/connection',
            method: 'POST',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/connection-init-post.js'),
            shortDescription: 'Initialize Salesforce connection secrets',
        },
        {
            $id: Now.ID['connection_get_route'],
            path: '/connection',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/connection-get.js'),
            shortDescription: 'Get current Salesforce connection details',
        },
        {
            $id: Now.ID['connection_status_route'],
            path: '/connection/status',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/connection-status-get.js'),
            shortDescription: 'Check if current user connection is valid',
        },
        {
            $id: Now.ID['connection_disconnect_route'],
            path: '/connection/disconnect',
            method: 'POST',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/connection-disconnect-post.js'),
            shortDescription: 'Disconnect current user Salesforce connection',
        },
        {
            $id: Now.ID['auth_route'],
            path: '/auth',
            method: 'POST',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-auth-post.js'),
            shortDescription: 'Handle Salesforce authentication',
        },
        {
            $id: Now.ID['task_types_route'],
            path: '/task-types',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/task-types-get.js'),
            shortDescription: 'Get available task types',
        },
        {
            $id: Now.ID['task_type_config_get_route'],
            path: '/task-type-config',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/task-type-config-get.js'),
            shortDescription: 'Get current task type configuration for connection',
        },
        {
            $id: Now.ID['task_type_config_put_route'],
            path: '/task-type-config',
            method: 'PUT',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/task-type-config-put.js'),
            shortDescription: 'Upsert task type configuration - updates existing or creates new',
        },
        {
            $id: Now.ID['salesforce_sobjects_route'],
            path: '/salesforce/sobjects',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-sobjects-get.js'),
            shortDescription: 'List Salesforce sObjects ("tables") available on the connected org',
        },
        {
            $id: Now.ID['sf_object_config_list_route'],
            path: '/salesforce/objects',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/sf-objects-config-get.js'),
            shortDescription: 'Get list of configured Salesforce objects to work with',
        },
        {
            $id: Now.ID['sf_object_config_add_route'],
            path: '/salesforce/objects',
            method: 'POST',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/sf-objects-config-post.js'),
            shortDescription: 'Add a Salesforce object to the configuration',
        },
        {
            $id: Now.ID['sf_object_config_delete_batch_route'],
            path: '/salesforce/objects/delete',
            method: 'POST',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/sf-objects-config-delete-batch-post.js'),
            shortDescription: 'Batch delete Salesforce objects from configuration (accepts array of objects with sys_id or sf_object_name)',
        },
        {
            $id: Now.ID['salesforce_search_all_route'],
            path: '/salesforce/search/all',
            method: 'POST',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-search-all-post.js'),
            shortDescription: 'Search across ALL configured Salesforce objects with a single query (automatically includes all active, searchable objects)',
        },
        {
            $id: Now.ID['salesforce_record_link_delete_route'],
            path: '/salesforce/record-link/delete',
            method: 'POST',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-record-link-delete-post.js'),
            shortDescription: 'Delete a link between a ServiceNow record and a Salesforce record (supports single or batch)',
        },

        {
            $id: Now.ID['salesforce_record_link_get_route'],
            path: '/salesforce/record-link',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-record-link-get.js'),
            shortDescription: 'Get linked Salesforce records for a ServiceNow record (requires servicenow_sys_id query parameter)',
        },

        {
            $id: Now.ID['salesforce_object_columns_add_route'],
            path: '/salesforce/objects/columns-add',
            method: 'POST',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-object-column-add-post.js'),
            shortDescription: 'Define displayable columns for a Salesforce object',
        },
        {
            $id: Now.ID['salesforce_object_columns_get_saved_route'],
            path: '/salesforce/objects/saved-columns-get',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-object-column-saved-get.js'),
            shortDescription: 'Get the list of saved columns for a Salesforce object',
        },
        {
            $id: Now.ID['salesforce_object_columns_get_route'],
            path: '/salesforce/objects/columns-get',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-object-get-columns.js'),
            shortDescription: 'Get the list of columns for a Salesforce object',
        },
        {
            $id: Now.ID['salesforce_object_describe_get_route'],
            path: '/salesforce/object/describe',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-object-describe-get.js'),
            shortDescription: 'Get the describe information for a Salesforce object',
        },
        {
            $id: Now.ID['salesforce_create_record'],
            path: '/salesforce/create-record',
            method: 'POST',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-create-record.js'),
            shortDescription: 'Create a new record in Salesforce',
        },
        {
            $id: Now.ID['salesforce_fetch_record_types_route'],
            path: '/salesforce/record-types',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-record-types-get.js'),
            shortDescription: 'Fetch the record types for a Salesforce object',
        },
        {
            $id: Now.ID['salesforce_lookup_suggestions_route'],
            path: '/salesforce/lookup-suggestions',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-lookup-suggestions-get.js'),
            shortDescription: 'Get lookup field suggestions for reference fields (search/autocomplete)',
        },
        {
            $id: Now.ID['salesforce_feed_route'],
            path: '/salesforce/get-feed',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-feed.js'),
            shortDescription: 'Get the feed for a Salesforce record',
        },
        {
            $id: Now.ID['salesforce_object_layout_route'],
            path: '/salesforce/object/layout',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-object-layout-get.js'),
            shortDescription: 'Get fields for a Salesforce object based on page layout (like Jira connector)',
        },
        {
            $id: Now.ID['salesforce_object_details'],
            path: '/salesforce/object/detail',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-object-detail.js'),
            shortDescription: 'Endpoint to fetch salesforce object details',
        },

        {
            $id: Now.ID['salesforce_related_objects_route'],
            path: '/salesforce/related-objects-get',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/related-objects-get.js'),
            shortDescription: 'Fetch all possible related objects for a Salesforce record',
        },
        {
            $id: Now.ID['salesforce_related_objects_select_route'],
            path: '/salesforce/related-objects-select',
            method: 'POST',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-related-objects-select-post.js'),
            shortDescription: 'Select related objects for a Salesforce record',
        },
        {
            $id: Now.ID['salesforce_related_objects_columns_route'],
            path: '/salesforce/related-objects-columns-get',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-related-objects-columns-get.js'),
            shortDescription: 'Get possible columns for a Salesforce related objects',
        },
        {
            $id: Now.ID['salesforce_related_objects_columns_select_route'],
            path: '/salesforce/related-objects-columns-select',
            method: 'POST',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-related-object-column-select.js'),
            shortDescription: 'Select columns for a Salesforce related objects',
        },
        {
            $id: Now.ID['salesforce_related_records_route'],
            path: '/salesforce/related-records',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-related-records-get.js'),
            shortDescription: 'Fetch all related (child) records for a Salesforce record, grouped by relationship',
        },
        {
            $id: Now.ID['salesforce_sync_post'],
            path: '/salesforce/sync',
            method: 'POST',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-sync-post.js'),
            shortDescription: 'Endpoint used for sync records between ServiceNow and Salesforce, to store all data on salesforce side.',
        },
        {
            $id: Now.ID['salesforce_org_settings_get'],
            path: '/salesforce/settings',
            method: 'GET',
            enforceAcl: [salesforceIntegrationRestEndpointAcl],
            script: Now.include('../../server/salesforce-org-settings-get.js'),
            shortDescription: 'Endpoint used for getting configurations from connected salesforce org.',
        },
    ],
})
